title = "Norton Kitagawa, Ph.D."
baseURL = "https://nortagawa.github.io/"
theme = "resume"
languageCode = "en-us"
PygmentsCodeFences = true
PygmentsCodeFencesGuessSyntax = true
PygmentsStyle = "monokai"
enableGitInfo = false

[params]
address = "San Francisco Bay Area"
email = "nkitagawa@gmail.com"
favicon = "/favicon.ico"
firstName = "Norton"
lastName = "Kitagawa"
phone = "1-408-598-1110"
profileImage = "img/Coffee_Headshot.jpg"
showEducation = true
showExperience = true
showOpenSource = false
showProjects = true
showPublications = false
showQr = false
showSkills = true

[[params.handles]]
link = "https://www.linkedin.com/in/nortagawa/"
name = "LinkedIn"

[[params.handles]]
link = "https://github.com/nortagawa/"
name = "GitHub"

[outputs]
home = ["HTML", "JSON"]

[taxonomies]
tag = "tags"